let vn=new Vue({
    el:'#app1',
    data:{
        pic:[
            {
                hre:"http://protobot.org",
                img:"img/boring_001.png",
                tit:"随机生成无厘头设计任务",
                recon:"很无聊"
            },
            {
                hre:"https://www.prettyscale.com/",
                img:"img/pic_111.png",
                tit:"在线颜值测评",
                recon:"是一个在线测试颜值的网友"
            },
            {
                hre:"https://www.stick-of-gum.com/",
                img:"img/pic_003.png",
                tit:"口香糖恶搞",
                recon:"可以在线用口香糖恶搞你的朋友"
            },
            {
                hre:"http://www.friv.com/",
                img:"img/boring_1252.png",
                tit:"264个好玩的FLASH游戏",
                recon:"页上陈列了264个FLASH游戏，每个游戏的左边都有详细的操作指南，游戏页面设计很完美，"
            },
            {
                hre:"https://mrdoob.com/projects/chromeexperiments/google-sphere/",
                img:"img/boring_32.png",
                tit:"Google Sphere",
                recon:"谷歌首页的元素形成了一个球体"
            },
            {
                hre:"https://baidujingzi.com/",
                img:"img/boring_67.png",
                tit:"百度镜子",
                recon:"镜子里的百度"
            },
            {
                hre:"http://flipanim.com/",
                img:"img/boring_094.ico",
                tit:"FlipAnim",
                recon:"可以手绘的网页"
            },
            {
                hre:"https://theuselessweb.com/",
                img:"img/boring_010.ico",
                tit:"Useless Web",
                recon:"点一下please就会弹出一个有无聊又好玩基本上没用的网站出来，玩一天根本停不下来"
            },
            {
                hre:"http://www.adoutu.com/index",
                img:"img/boring_055.ico",
                tit:"爱斗图",
                recon:"论表情包的重要性"
            },
            {
                hre:"http://kedou.workerman.net/",
                img:"img/boring_01.ico",
                tit:"小蝌蚪互动聊天室",
                recon:"就是个匿名聊天室，直接在屏幕上打字就可以聊天"
            },
            {
                hre:"https://mrdoob.com/lab/javascript/effects/solitaire/",
                img:"img/boring_003.ico",
                tit:" 跳跃的扑克牌",
                recon:"点击鼠标就会有扑克牌跳下来并且不断地弹弹弹一直到弹出屏幕"
            },
            {
                hre:"https://www.humancalendar.com/",
                img:"img/boring_009.ico",
                tit:"创意真人日历",
                recon:"有创意的在线真人版日历，所有天数和星期都由人物图片构成，日历上所有的人，都会看着拿今天日期牌子的那个人"
            },
            {
                hre:"http://www.20q.net/",
                img:"img/boring_618.gif",
                tit:"猜出你在想什么",
                recon:"想象一个物体，然后回答20个小问题，系统就能猜出来你想的是什么"
            },
            {
                hre:"http://www.dayong.name/",
                img:"img/boring_004.ico",
                tit:"大勇和小花的旅行日记",
                recon:"日记里的男女主角——大勇和小花，他们用浪漫背包旅行记录着点滴爱情。一个负责摄影，一个负责文字，一路走来，携手看尽细水流长"
            },
            {
                hre:"https://www.rainymood.com/",
                img:"img/boring_008.ico",
                tit:"听雨声",
                recon:"打开此网站后，里面会一直都在下雨，雨声能让烦躁的心慢慢平静下来。"
            }
        ],
        hot:[
            {
                link:"http://protobot.org",
                tit:"1.随机生成无厘头设计任务"
            },
            {
                link:"https://www.rainymood.com/",
                tit:"2.听雨声"
            },
            {
                link:"http://www.dayong.name/",
                tit:"3.大勇和小花的旅行日记"
            },
            {
                link:"http://www.20q.net/",
                tit:"4.猜出你在想什么"
            },
            {
                link:"https://mrdoob.com/lab/javascript/effects/solitaire/",
                tit:"5.跳跃的扑克牌"
            },
            {
                link:"http://www.adoutu.com/index",
                tit:"6.爱斗图"
            },
            {
                link:"http://flipanim.com/",
                tit:"7.FlipAnim"
            },
            {
                link:"https://theuselessweb.com/",
                tit:"8.Useless Web"
            },
            {
                link:"http://www.friv.com/",
                tit:"9.264个好玩的FLASH游戏"
            },
            {
                link:"https://mrdoob.com/projects/chromeexperiments/google-sphere/",
                tit:"10.Google Sphere"
            }
        ]
    }
});
function closeNav(){
    document.getElementById("side").style.display = "none";
}
function openNav(){
    document.getElementById("side").style.display = "block";

}