let vn=new Vue({
    el:'#app1',
    data:{
        pic:[
            {
                hre:"http://nazo.one-story.cn/",
                img:"img/pic01.ico",
                tit:"Nazo Game",
                recon:"是一个计算机有关的解密小游戏"
            },
            {
                hre:"http://diep.io/",
                img:"img/pic_010.png",
                tit:"Diep",
                recon:"每个玩家都是一枚小坦克，点击鼠标发射炮弹（红点点）"
            },
            {
                hre:"http://slither.io/",
                img:"img/game_002.png",
                tit:"Slither",
                recon:"多人在线游戏，鼠标控制一条蚯蚓，通过吃周围发光的点来变粗变长"
            },
            {
                hre:"http://flapmmo.com/",
                img:"img/game_003.png",
                tit:"Squishybird ",
                recon:"这个就是flappybird，但是不同的是它是个多人在线游戏"
            },
            {
                hre:"https://geoguessr.com/",
                img:"img/game_046.ico",
                tit:"GeoGuessr",
                recon:"给你任意一个地方的google街景，让你猜测这是哪里，并在图中右下角的世界地图上做标记"
            },
            {
                hre:"https://lines.frvr.com/",
                img:"img/game_035.png",
                tit:"Play Lines",
                recon:"就是把相同颜色的点都连接起来，路径不能有重叠"
            },
            {
                hre:"https://hex.frvr.com/",
                img:"img/game_027.png",
                tit:" Hexagon",
                recon:"玩法和1010相同，把右侧随机出现的色块放进六边形的“棋盘”里，每填满一行或一斜列就能消除，同时消除多行/列有附加分。"
            },
            {
                hre:"https://aidn.jp/mikutap/",
                img:"img/game_050.ico",
                tit:"Mikutap",
                recon:"带上耳机，能玩很久"
            },
            {
                hre:"http://mope.io/",
                img:"img/game_004.png",
                tit:"mope",
                recon:".io游戏，吃经验，防止老鹰"
            },
            {
                hre:"http://green.ssyar.com/",
                img:"img/game_005.png",
                tit:"原谅帽大作战",
                recon:"听名字就很魔性"
            },
            {
                hre:"http://play.ziyuantun.com/",
                img:"img/game_002.ico",
                tit:"资源屯·欢乐时光",
                recon:"里面有一些好玩的小游戏"
            },
            {
                hre:"https://gfw.tapirgames.com/",
                img:"img/game_06.png",
                tit:"貘艺",
                recon:"里面也有一些好玩的小游戏"
            },
            {
                hre:"https://www.linerider.com/",
                img:"img/game_006.ico",
                tit:"线条骑行者",
                recon:"用线条画一条线，小人就会沿着轨迹走。订制一条特殊的路线，让小人在你的线条上翻跟斗滑下去"
            },
            {
                hre:"http://hell.one-story.cn/hell-start.html",
                img:"img/game_007.png",
                tit:"hell.one-story",
                recon:"也是一个计算机有关的解密小游戏"
            },
            {
                hre:"http://weavesilk.com/",
                img:"img/game_008.png",
                tit:"silk",
                recon:"一个对称绘画的网站"
            }
        ],
        hot:[
            {
                link:"http://hell.one-story.cn/hell-start.html",
                tit:"1.hell.one-story"
            },
            {
                link:"http://nazo.one-story.cn/",
                tit:"2.Nazo Game"
            },
            {
                link:"http://weavesilk.com/",
                tit:"3.silk"
            },
            {
                link:"https://gfw.tapirgames.com/",
                tit:"4.貘艺"
            },
            {
                link:"http://green.ssyar.com/",
                tit:"5.原谅帽大作战"
            },
            {
                link:"https://geoguessr.com/",
                tit:"6.GeoGuessr"
            },
            {
                link:"http://diep.io/",
                tit:"7.Diep"
            },
            {
                link:"http://slither.io/",
                tit:"8.Slither"
            },
            {
                link:"http://play.ziyuantun.com/",
                tit:"9.资源屯·欢乐时光"
            },
            {
                link:"http://diep.io/",
                tit:"10.Diep"
            }
        ]
    }
});
function closeNav(){
    document.getElementById("side").style.display = "none";
}
function openNav(){
    document.getElementById("side").style.display = "block";

}